import { ThemeOverrides, YumiaTheme } from './types.js';

export const defaultTheme: YumiaTheme = {
  name: 'default',
  description: 'Default modern theme with high contrast and clean typography',
  colors: {
    primary: '#2563eb',
    secondary: '#7c3aed',
    background: '#ffffff',
    surface: '#f8fafc',
    elevatedSurface: '#ffffff',
    text: '#0f172a',
    muted: '#64748b',
    accent: '#06b6d4',
    border: '#e2e8f0',
    divider: '#cbd5e1',
    success: '#10b981',
    warning: '#f59e0b',
    danger: '#ef4444',
    info: '#3b82f6',
  },
  typography: {
    headingFont: 'Inter, system-ui, -apple-system, sans-serif',
    bodyFont: 'Inter, system-ui, -apple-system, sans-serif',
    codeFont: 'JetBrains Mono, Fira Code, monospace',
    sizes: {
      display: 56,
      h1: 44,
      h2: 36,
      h3: 28,
      h4: 22,
      body: 18,
      small: 14,
      caption: 12,
      code: 16,
      quote: 20,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.5,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.04em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 16,
    xl: 24,
    full: 9999,
    default: 8,
  },
  shadows: {
    none: 'none',
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    glow: '0 0 15px rgba(37, 99, 235, 0.35)',
  },
  components: {
    card: {
      background: '#f8fafc',
      borderColor: '#e2e8f0',
      borderRadius: 12,
      padding: 24,
    },
    metric: {
      valueColor: '#2563eb',
      labelColor: '#64748b',
      borderRadius: 12,
    },
    code: {
      background: '#0f172a',
      textColor: '#f8fafc',
      borderRadius: 8,
    },
    table: {
      headerBackground: '#f1f5f9',
      rowAlternateBackground: '#f8fafc',
      borderColor: '#e2e8f0',
    },
  },
};

export const cyberpunkTheme: YumiaTheme = {
  name: 'cyberpunk',
  description: 'High-energy dark cyberpunk theme with neon pink and cyan accents',
  colors: {
    primary: '#FF2E88',
    secondary: '#00F0FF',
    background: '#0B0B12',
    surface: '#151522',
    elevatedSurface: '#1D1D2E',
    text: '#FFFFFF',
    muted: '#A7A7B5',
    accent: '#7B61FF',
    border: '#2E2E48',
    divider: '#3E3E5E',
    success: '#00FF9F',
    warning: '#FFE600',
    danger: '#FF0055',
    info: '#00F0FF',
  },
  typography: {
    headingFont: 'Outfit, Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
    codeFont: 'JetBrains Mono, monospace',
    sizes: {
      display: 58,
      h1: 46,
      h2: 38,
      h3: 28,
      h4: 22,
      body: 18,
      small: 14,
      caption: 12,
      code: 16,
      quote: 20,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.55,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.05em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 28,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 6,
    md: 12,
    lg: 20,
    xl: 28,
    full: 9999,
    default: 12,
  },
  shadows: {
    none: 'none',
    sm: '0 2px 4px rgba(0, 0, 0, 0.4)',
    md: '0 8px 16px rgba(0, 0, 0, 0.6)',
    lg: '0 16px 32px rgba(0, 0, 0, 0.8)',
    glow: '0 0 20px rgba(255, 46, 136, 0.45)',
  },
  components: {
    card: {
      background: '#151522',
      borderColor: '#FF2E88',
      borderRadius: 16,
      padding: 28,
    },
    metric: {
      valueColor: '#FF2E88',
      labelColor: '#A7A7B5',
      borderRadius: 16,
    },
    code: {
      background: '#07070D',
      textColor: '#00F0FF',
      borderRadius: 8,
    },
    table: {
      headerBackground: '#1D1D2E',
      rowAlternateBackground: '#151522',
      borderColor: '#2E2E48',
    },
  },
};

export const minimalTheme: YumiaTheme = {
  name: 'minimal',
  description: 'Monochrome Swiss-style design with maximum clarity and contrast',
  colors: {
    primary: '#111111',
    secondary: '#333333',
    background: '#FFFFFF',
    surface: '#F5F5F7',
    elevatedSurface: '#FFFFFF',
    text: '#111111',
    muted: '#777777',
    accent: '#000000',
    border: '#E5E5E5',
    divider: '#D1D1D6',
    success: '#10B981',
    warning: '#F59E0B',
    danger: '#EF4444',
    info: '#3B82F6',
  },
  typography: {
    headingFont: 'Helvetica Neue, Arial, sans-serif',
    bodyFont: 'Helvetica Neue, Arial, sans-serif',
    codeFont: 'Menlo, Monaco, monospace',
    sizes: {
      display: 54,
      h1: 44,
      h2: 34,
      h3: 26,
      h4: 20,
      body: 18,
      small: 14,
      caption: 12,
      code: 15,
      quote: 19,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.25,
      normal: 1.5,
      relaxed: 1.65,
    },
    letterSpacing: {
      tight: '-0.03em',
      normal: '0em',
      wide: '0.02em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 56,
    elementGap: 24,
    safeArea: { top: 56, bottom: 56, left: 56, right: 56 },
  },
  radius: {
    none: 0,
    sm: 2,
    md: 4,
    lg: 8,
    xl: 12,
    full: 9999,
    default: 4,
  },
  shadows: {
    none: 'none',
    sm: '0 1px 3px rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px rgba(0, 0, 0, 0.07)',
    lg: '0 10px 15px rgba(0, 0, 0, 0.08)',
    glow: 'none',
  },
  components: {
    card: {
      background: '#F5F5F7',
      borderColor: '#E5E5E5',
      borderRadius: 6,
      padding: 24,
    },
    metric: {
      valueColor: '#111111',
      labelColor: '#777777',
      borderRadius: 6,
    },
    code: {
      background: '#1C1C1E',
      textColor: '#F2F2F7',
      borderRadius: 4,
    },
    table: {
      headerBackground: '#EBEBEF',
      rowAlternateBackground: '#F5F5F7',
      borderColor: '#E5E5E5',
    },
  },
};

export const corporateTheme: YumiaTheme = {
  name: 'corporate',
  description: 'Executive navy blue palette tailored for business and enterprise decks',
  colors: {
    primary: '#0A2540',
    secondary: '#635BFF',
    background: '#FFFFFF',
    surface: '#F8FAFC',
    elevatedSurface: '#FFFFFF',
    text: '#1A1F36',
    muted: '#4F566B',
    accent: '#00D4B2',
    border: '#E3E8EE',
    divider: '#CBD5E1',
    success: '#00D4B2',
    warning: '#FFC043',
    danger: '#DF1B41',
    info: '#635BFF',
  },
  typography: {
    headingFont: 'Inter, Segoe UI, sans-serif',
    bodyFont: 'Inter, Segoe UI, sans-serif',
    codeFont: 'Consolas, monospace',
    sizes: {
      display: 54,
      h1: 42,
      h2: 34,
      h3: 26,
      h4: 20,
      body: 18,
      small: 14,
      caption: 12,
      code: 15,
      quote: 19,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.5,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.02em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 12,
    xl: 18,
    full: 9999,
    default: 8,
  },
  shadows: {
    none: 'none',
    sm: '0 1px 3px rgba(10, 37, 64, 0.05)',
    md: '0 4px 8px rgba(10, 37, 64, 0.08)',
    lg: '0 12px 24px rgba(10, 37, 64, 0.12)',
    glow: '0 0 12px rgba(0, 212, 178, 0.25)',
  },
  components: {
    card: {
      background: '#F8FAFC',
      borderColor: '#0A2540',
      borderRadius: 8,
      padding: 24,
    },
    metric: {
      valueColor: '#0A2540',
      labelColor: '#4F566B',
      borderRadius: 8,
    },
    code: {
      background: '#0A2540',
      textColor: '#00D4B2',
      borderRadius: 6,
    },
    table: {
      headerBackground: '#E3E8EE',
      rowAlternateBackground: '#F8FAFC',
      borderColor: '#CBD5E1',
    },
  },
};

export const terminalTheme: YumiaTheme = {
  name: 'terminal',
  description: 'Retro hacker green-on-dark theme with pure monospace aesthetic',
  colors: {
    primary: '#00FF66',
    secondary: '#33FF88',
    background: '#0C100C',
    surface: '#141A14',
    elevatedSurface: '#1C241C',
    text: '#E0FFE0',
    muted: '#4E7A4E',
    accent: '#FFB000',
    border: '#1F331F',
    divider: '#2A442A',
    success: '#00FF66',
    warning: '#FFB000',
    danger: '#FF3333',
    info: '#00E5FF',
  },
  typography: {
    headingFont: 'JetBrains Mono, Courier New, monospace',
    bodyFont: 'JetBrains Mono, Courier New, monospace',
    codeFont: 'JetBrains Mono, Courier New, monospace',
    sizes: {
      display: 50,
      h1: 40,
      h2: 32,
      h3: 26,
      h4: 20,
      body: 17,
      small: 13,
      caption: 11,
      code: 15,
      quote: 18,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.5,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '0em',
      normal: '0em',
      wide: '0.04em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 0,
    md: 0,
    lg: 0,
    xl: 0,
    full: 0,
    default: 0,
  },
  shadows: {
    none: 'none',
    sm: 'none',
    md: 'none',
    lg: 'none',
    glow: '0 0 15px rgba(0, 255, 102, 0.4)',
  },
  components: {
    card: {
      background: '#141A14',
      borderColor: '#00FF66',
      borderRadius: 0,
      padding: 24,
    },
    metric: {
      valueColor: '#00FF66',
      labelColor: '#4E7A4E',
      borderRadius: 0,
    },
    code: {
      background: '#070A07',
      textColor: '#00FF66',
      borderRadius: 0,
    },
    table: {
      headerBackground: '#1F331F',
      rowAlternateBackground: '#141A14',
      borderColor: '#2A442A',
    },
  },
};

export const academicTheme: YumiaTheme = {
  name: 'academic',
  description: 'Scholarly paper theme with serif typography and crimson accents',
  colors: {
    primary: '#8B0000',
    secondary: '#1C3F60',
    background: '#FCFBF7',
    surface: '#F5F2EB',
    elevatedSurface: '#FFFFFF',
    text: '#2C2B29',
    muted: '#6B6862',
    accent: '#C29B38',
    border: '#E0DACD',
    divider: '#D5CDBE',
    success: '#2E7D32',
    warning: '#E65100',
    danger: '#C62828',
    info: '#1565C0',
  },
  typography: {
    headingFont: 'Georgia, Times New Roman, serif',
    bodyFont: 'Georgia, Times New Roman, serif',
    codeFont: 'Courier New, monospace',
    sizes: {
      display: 54,
      h1: 42,
      h2: 34,
      h3: 26,
      h4: 20,
      body: 18,
      small: 14,
      caption: 12,
      code: 15,
      quote: 19,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.55,
      relaxed: 1.75,
    },
    letterSpacing: {
      tight: '-0.01em',
      normal: '0em',
      wide: '0.03em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 52,
    elementGap: 24,
    safeArea: { top: 52, bottom: 52, left: 52, right: 52 },
  },
  radius: {
    none: 0,
    sm: 2,
    md: 4,
    lg: 6,
    xl: 10,
    full: 9999,
    default: 4,
  },
  shadows: {
    none: 'none',
    sm: '0 1px 3px rgba(44, 43, 41, 0.05)',
    md: '0 3px 6px rgba(44, 43, 41, 0.08)',
    lg: '0 8px 16px rgba(44, 43, 41, 0.1)',
    glow: 'none',
  },
  components: {
    card: {
      background: '#F5F2EB',
      borderColor: '#8B0000',
      borderRadius: 4,
      padding: 24,
    },
    metric: {
      valueColor: '#8B0000',
      labelColor: '#6B6862',
      borderRadius: 4,
    },
    code: {
      background: '#2C2B29',
      textColor: '#F5F2EB',
      borderRadius: 4,
    },
    table: {
      headerBackground: '#E0DACD',
      rowAlternateBackground: '#F5F2EB',
      borderColor: '#D5CDBE',
    },
  },
};

export const nordTheme: YumiaTheme = {
  name: 'nord',
  description: 'Arctic, north-bluish clean dark palette for elegant developer decks',
  colors: {
    primary: '#88C0D0',
    secondary: '#81A1C1',
    background: '#2E3440',
    surface: '#3B4252',
    elevatedSurface: '#434C5E',
    text: '#ECEFF4',
    muted: '#D8DEE9',
    accent: '#5E81AC',
    border: '#4C566A',
    divider: '#434C5E',
    success: '#A3BE8C',
    warning: '#EBCB8B',
    danger: '#BF616A',
    info: '#88C0D0',
  },
  typography: {
    headingFont: 'Inter, system-ui, sans-serif',
    bodyFont: 'Inter, system-ui, sans-serif',
    codeFont: 'JetBrains Mono, Fira Code, monospace',
    sizes: {
      display: 56,
      h1: 44,
      h2: 36,
      h3: 28,
      h4: 22,
      body: 18,
      small: 14,
      caption: 12,
      code: 16,
      quote: 20,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.55,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.03em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 14,
    xl: 20,
    full: 9999,
    default: 8,
  },
  shadows: {
    none: 'none',
    sm: '0 2px 4px rgba(0, 0, 0, 0.25)',
    md: '0 6px 12px rgba(0, 0, 0, 0.35)',
    lg: '0 12px 24px rgba(0, 0, 0, 0.45)',
    glow: '0 0 16px rgba(136, 192, 208, 0.35)',
  },
  components: {
    card: {
      background: '#3B4252',
      borderColor: '#88C0D0',
      borderRadius: 10,
      padding: 24,
    },
    metric: {
      valueColor: '#88C0D0',
      labelColor: '#D8DEE9',
      borderRadius: 10,
    },
    code: {
      background: '#242933',
      textColor: '#ECEFF4',
      borderRadius: 8,
    },
    table: {
      headerBackground: '#434C5E',
      rowAlternateBackground: '#3B4252',
      borderColor: '#4C566A',
    },
  },
};

export const draculaTheme: YumiaTheme = {
  name: 'dracula',
  description: 'Famous dark theme with rich purples, vibrant pinks and pastel highlights',
  colors: {
    primary: '#BD93F9',
    secondary: '#FF79C6',
    background: '#282A36',
    surface: '#343746',
    elevatedSurface: '#44475A',
    text: '#F8F8F2',
    muted: '#6272A4',
    accent: '#8BE9FD',
    border: '#44475A',
    divider: '#6272A4',
    success: '#50FA7B',
    warning: '#F1FA8C',
    danger: '#FF5555',
    info: '#8BE9FD',
  },
  typography: {
    headingFont: 'Outfit, Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
    codeFont: 'Fira Code, JetBrains Mono, monospace',
    sizes: {
      display: 56,
      h1: 44,
      h2: 36,
      h3: 28,
      h4: 22,
      body: 18,
      small: 14,
      caption: 12,
      code: 16,
      quote: 20,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.55,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.03em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 4,
    md: 10,
    lg: 16,
    xl: 24,
    full: 9999,
    default: 10,
  },
  shadows: {
    none: 'none',
    sm: '0 2px 5px rgba(0, 0, 0, 0.3)',
    md: '0 8px 16px rgba(0, 0, 0, 0.45)',
    lg: '0 16px 32px rgba(0, 0, 0, 0.6)',
    glow: '0 0 20px rgba(189, 147, 249, 0.4)',
  },
  components: {
    card: {
      background: '#343746',
      borderColor: '#BD93F9',
      borderRadius: 12,
      padding: 24,
    },
    metric: {
      valueColor: '#FF79C6',
      labelColor: '#6272A4',
      borderRadius: 12,
    },
    code: {
      background: '#1E1F29',
      textColor: '#F8F8F2',
      borderRadius: 8,
    },
    table: {
      headerBackground: '#44475A',
      rowAlternateBackground: '#343746',
      borderColor: '#6272A4',
    },
  },
};

export const tokyoNightTheme: YumiaTheme = {
  name: 'tokyo-night',
  description: 'Sleek Tokyo Night neon indigo theme with cyan, violet and magenta tones',
  colors: {
    primary: '#7AA2F7',
    secondary: '#BB9AF7',
    background: '#1A1B26',
    surface: '#24283B',
    elevatedSurface: '#2F354A',
    text: '#C0CAF5',
    muted: '#565F89',
    accent: '#7DCFFF',
    border: '#2F354A',
    divider: '#414868',
    success: '#9ECE6A',
    warning: '#E0AF68',
    danger: '#F7768E',
    info: '#7DCFFF',
  },
  typography: {
    headingFont: 'Outfit, Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
    codeFont: 'JetBrains Mono, monospace',
    sizes: {
      display: 58,
      h1: 46,
      h2: 36,
      h3: 28,
      h4: 22,
      body: 18,
      small: 14,
      caption: 12,
      code: 16,
      quote: 20,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.55,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.03em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 6,
    md: 10,
    lg: 16,
    xl: 24,
    full: 9999,
    default: 10,
  },
  shadows: {
    none: 'none',
    sm: '0 2px 4px rgba(0, 0, 0, 0.3)',
    md: '0 6px 14px rgba(0, 0, 0, 0.45)',
    lg: '0 14px 28px rgba(0, 0, 0, 0.6)',
    glow: '0 0 18px rgba(122, 162, 247, 0.4)',
  },
  components: {
    card: {
      background: '#24283B',
      borderColor: '#7AA2F7',
      borderRadius: 12,
      padding: 24,
    },
    metric: {
      valueColor: '#7AA2F7',
      labelColor: '#565F89',
      borderRadius: 12,
    },
    code: {
      background: '#16161E',
      textColor: '#C0CAF5',
      borderRadius: 8,
    },
    table: {
      headerBackground: '#2F354A',
      rowAlternateBackground: '#24283B',
      borderColor: '#414868',
    },
  },
};

export const emeraldTheme: YumiaTheme = {
  name: 'emerald',
  description: 'Deep forest luxury green with mint and emerald highlights',
  colors: {
    primary: '#10B981',
    secondary: '#34D399',
    background: '#022C22',
    surface: '#064E3B',
    elevatedSurface: '#065F46',
    text: '#ECFDF5',
    muted: '#6EE7B7',
    accent: '#A7F3D0',
    border: '#047857',
    divider: '#065F46',
    success: '#34D399',
    warning: '#FBBF24',
    danger: '#F87171',
    info: '#38BDF8',
  },
  typography: {
    headingFont: 'Outfit, Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
    codeFont: 'JetBrains Mono, monospace',
    sizes: {
      display: 56,
      h1: 44,
      h2: 36,
      h3: 28,
      h4: 22,
      body: 18,
      small: 14,
      caption: 12,
      code: 16,
      quote: 20,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.55,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.03em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 16,
    xl: 24,
    full: 9999,
    default: 8,
  },
  shadows: {
    none: 'none',
    sm: '0 2px 4px rgba(0, 0, 0, 0.3)',
    md: '0 6px 14px rgba(0, 0, 0, 0.45)',
    lg: '0 14px 28px rgba(0, 0, 0, 0.6)',
    glow: '0 0 18px rgba(16, 185, 129, 0.4)',
  },
  components: {
    card: {
      background: '#064E3B',
      borderColor: '#10B981',
      borderRadius: 12,
      padding: 24,
    },
    metric: {
      valueColor: '#10B981',
      labelColor: '#6EE7B7',
      borderRadius: 12,
    },
    code: {
      background: '#011A14',
      textColor: '#ECFDF5',
      borderRadius: 8,
    },
    table: {
      headerBackground: '#065F46',
      rowAlternateBackground: '#064E3B',
      borderColor: '#047857',
    },
  },
};

export const synthwaveTheme: YumiaTheme = {
  name: 'synthwave',
  description: '80s retro neon sunset with hot pink, glowing cyan and electric violet',
  colors: {
    primary: '#FF71CE',
    secondary: '#01CDFE',
    background: '#1A0E2E',
    surface: '#261447',
    elevatedSurface: '#351B63',
    text: '#FFFFFF',
    muted: '#B967FF',
    accent: '#05FFA1',
    border: '#4D288C',
    divider: '#6432B8',
    success: '#05FFA1',
    warning: '#FFFB96',
    danger: '#FF2A6D',
    info: '#01CDFE',
  },
  typography: {
    headingFont: 'Outfit, Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
    codeFont: 'Fira Code, monospace',
    sizes: {
      display: 58,
      h1: 46,
      h2: 38,
      h3: 28,
      h4: 22,
      body: 18,
      small: 14,
      caption: 12,
      code: 16,
      quote: 20,
      metadata: 12,
    },
    weights: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.55,
      relaxed: 1.7,
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0em',
      wide: '0.04em',
    },
  },
  spacing: {
    unit: 8,
    scale: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96],
    slidePadding: 48,
    elementGap: 24,
    safeArea: { top: 48, bottom: 48, left: 48, right: 48 },
  },
  radius: {
    none: 0,
    sm: 6,
    md: 12,
    lg: 18,
    xl: 26,
    full: 9999,
    default: 12,
  },
  shadows: {
    none: 'none',
    sm: '0 2px 6px rgba(0, 0, 0, 0.4)',
    md: '0 8px 18px rgba(0, 0, 0, 0.6)',
    lg: '0 16px 36px rgba(0, 0, 0, 0.75)',
    glow: '0 0 22px rgba(255, 113, 206, 0.5)',
  },
  components: {
    card: {
      background: '#261447',
      borderColor: '#FF71CE',
      borderRadius: 14,
      padding: 24,
    },
    metric: {
      valueColor: '#FF71CE',
      labelColor: '#B967FF',
      borderRadius: 14,
    },
    code: {
      background: '#11091F',
      textColor: '#05FFA1',
      borderRadius: 8,
    },
    table: {
      headerBackground: '#351B63',
      rowAlternateBackground: '#261447',
      borderColor: '#4D288C',
    },
  },
};

export const THEME_REGISTRY: Record<string, YumiaTheme> = {
  default: defaultTheme,
  cyberpunk: cyberpunkTheme,
  minimal: minimalTheme,
  corporate: corporateTheme,
  terminal: terminalTheme,
  academic: academicTheme,
  nord: nordTheme,
  dracula: draculaTheme,
  'tokyo-night': tokyoNightTheme,
  tokyonight: tokyoNightTheme,
  midnight: tokyoNightTheme,
  emerald: emeraldTheme,
  forest: emeraldTheme,
  synthwave: synthwaveTheme,
  sunset: synthwaveTheme,
};

export function resolveTheme(
  themeNameOrRef?: string | { name: string; overrides?: ThemeOverrides },
  explicitOverrides?: ThemeOverrides
): YumiaTheme {
  const name =
    typeof themeNameOrRef === 'string' ? themeNameOrRef : themeNameOrRef?.name || 'default';

  const baseTheme = THEME_REGISTRY[name.toLowerCase()] || defaultTheme;
  const refOverrides = typeof themeNameOrRef === 'object' ? themeNameOrRef.overrides : undefined;

  const mergedOverrides: ThemeOverrides = {
    ...refOverrides,
    ...explicitOverrides,
    colors: { ...baseTheme.colors, ...refOverrides?.colors, ...explicitOverrides?.colors },
    typography: {
      ...baseTheme.typography,
      ...refOverrides?.typography,
      ...explicitOverrides?.typography,
      sizes: {
        ...baseTheme.typography.sizes,
        ...refOverrides?.typography?.sizes,
        ...explicitOverrides?.typography?.sizes,
      },
      weights: {
        ...baseTheme.typography.weights,
        ...refOverrides?.typography?.weights,
        ...explicitOverrides?.typography?.weights,
      },
      lineHeights: {
        ...baseTheme.typography.lineHeights,
        ...refOverrides?.typography?.lineHeights,
        ...explicitOverrides?.typography?.lineHeights,
      },
    },
    spacing: {
      ...baseTheme.spacing,
      ...refOverrides?.spacing,
      ...explicitOverrides?.spacing,
      safeArea: {
        ...baseTheme.spacing.safeArea,
        ...refOverrides?.spacing?.safeArea,
        ...explicitOverrides?.spacing?.safeArea,
      },
    },
    radius: {
      ...baseTheme.radius,
      ...refOverrides?.radius,
      ...explicitOverrides?.radius,
    },
    shadows: {
      ...baseTheme.shadows,
      ...refOverrides?.shadows,
      ...explicitOverrides?.shadows,
    },
    components: {
      ...baseTheme.components,
      ...refOverrides?.components,
      ...explicitOverrides?.components,
    },
  };

  return {
    ...baseTheme,
    ...mergedOverrides,
  } as YumiaTheme;
}

export function createTheme(overrides: ThemeOverrides & { name: string }): YumiaTheme {
  return resolveTheme(overrides.name, overrides);
}
